---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pixie-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pixie-operator-role
subjects:
- kind: ServiceAccount
  name: pixie-operator-service-account
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pixie-operator-role
rules:
# Allow actions on Kubernetes objects
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  - extensions
  - etcd.database.coreos.com
  - batch
  - nats.io
  - policy
  - apiextensions.k8s.io
  - px.dev
  resources:
  - clusterroles
  - clusterrolebindings
  - configmaps
  - customresourcedefinitions
  - secrets
  - pods
  - services
  - deployments
  - daemonsets
  - persistentvolumes
  - persistentvolumeclaims
  - roles
  - rolebindings
  - serviceaccounts
  - etcdclusters.etcd.database.coreos.com
  - etcdclusters
  - statefulsets
  - cronjobs
  - jobs
  - natsclusters
  - podsecuritypolicies
  - viziers
  - viziers/status
  verbs: ["*"]
