apiVersion: apps/v1
kind: Deployment
metadata:
  name: artifact-tracker-server
spec:
  template:
    spec:
      containers:
      - name: artifact-tracker-server
        env:
        - name: PL_VIZIER_VERSION
          value: "0.7.8"
        - name: PL_CLI_VERSION
          value: "0.5.8"
        - name: PL_OPERATOR_VERSION
          value: "0.1.0"
